### ISSUE TITLE
How to reuse DWPose video?

### ISSUE THREAD

**Issue by SoaringTiger** [dvlab-research/ControlNeXt#17]
Can I directly use the DWPose action MP4 as an input parameter, so I can reuse DWPose  video without having to regenerate it every time ?

**Comment by cly2625** [comment]
Try MimicMotion ？

**Comment by Pbihao** [comment]
[There is a pose alignment process that first extracts pose information and then maps the source pose video coordinates to the reference image's human pose. For more details, please refer to [this](https://github.com/dvlab-research/ControlNeXt/blob/main/ControlNeXt-SVD-v2/dwpose/preprocess.py) https://github.com/dvlab-research/ControlNeXt/blob/main/ControlNeXt-SVD-v2/dwpose/preprocess.py

Certainly, you can directly store the pose coordinates and apply the mapping during inference. This mapping is essential because SVD tends to perform poorly when generating large motion sequences.
