### ISSUE TITLE
anyone reproduced the example of ControlNeXt SVD/outputs/chair/chair.mp4

### ISSUE THREAD

**Issue by FourTest** [dvlab-research/ControlNeXt#50]
Has anyone reproduced the example of ControlNeXt SVD/outputs/chair/chair.mp4? This is the result I generated with pretrained/unet_fp16.bin :

https://github.com/user-attachments/assets/b8bdcd38-71b5-4628-9a5e-bba4cf7656a5

and this is the result I generated with fintuned/unet_fp16.bin :

https://github.com/user-attachments/assets/e52860c6-05fe-4d7f-8476-2cb5057871ed

the refImage:
![chair](https://github.com/user-attachments/assets/431f98a3-a377-45a8-9c03-7ec8996ba4c6)

**Comment by Pbihao** [comment]
Thank you for your interest!

hhhhhhhhhh! This is a humorous example I came across during evaluation, so I thought I'd share it.

Here’s the context: This result comes from the V1 version, where we didn't conduct continual pretraining on human-related videos and only trained the 'to_out' sub-parameters.

So, it's a trade-off. More trainable parameters lead to better performance on human-related videos but with reduced robustness—makes sense, right?

In the end, we decided to prioritize performance over robustness. If you'd like, you can train a version without continual pretraining, focusing on the sub-parameters, since we've provided the training scripts.
